import { useEffect } from "react";
import { useLocation } from "react-router-dom";
import "jspdf-autotable";
import jsPDF from "jspdf";

const Header = () => {
  return (
    <div
      className="text-center mt-3"
      style={{ fontSize: "20px", color: "black", float: "left" }}
    >
      <span className="display-6" style={{ fontWeight: "bold" }}>
        Project Evaluation
      </span>
    </div>
  );
};

const Table = () => {
  let location = useLocation();
  let projectId = "";
  let projectName = "";
  let projectManager = "";
  let description = "";
  let employeeList = [];
  let sprints = 0;

  projectId = location.state.projectId;
  projectName = location.state.title;
  projectManager = location.state.projectManager;
  description = location.state.description;
  employeeList = location.state.employeeList;
  sprints = location.state.sprints;

  const empData = [
    {projectId: projectId,
    projectManager: projectManager.name,
    description: description,
    noOfSprints: sprints,
    employeeList: employeeList.map((emp) => `${emp.firstName} ${emp.lastName}`),
}  ];

  console.log(projectManager.name);

  const columns = [
    { title: "Project Id", field: "projectId" },
    { title: "Project Manager", field: "projectManager" },
    { title: "Description", field: "description" },
    { title: "No of Sprints", field: "noOfSprints", type: "numeric" },
    { title: "Employee List", field: "employeeList" },
  ];
    const generatePDF = () => {
      const doc = new jsPDF();
      doc.text(`${projectName} Project Report`, 30, 10);
      doc.autoTable({
          columns: columns.map((col) => ({
              ...col,
              dataKey: col.field,
          })),
          body: empData,
      });
      doc.text(`Date: ${new Date().toLocaleDateString()}`, 10, 70);
      doc.text(`Time: ${new Date().toLocaleTimeString()}`, 10, 80);
      doc.text(`Generated By: ${projectManager.name}`, 10, 90);
    doc.save(`${projectName} Project Report.pdf`);
  };
  console.log(projectManager.name);

  return (
    <div className="mt-3 mx-5 px-2">
      <div className="card boderRadiusCards px-5">
        <div className="card-body">
          <div className="container">
            <div className="row">
              <div className="col-lg-12">
                <div className="d-flex justify-content-between">
                  <h3>{projectName}</h3>
                  <button className="btn btn-dark" onClick={generatePDF}>
                    Download Report
                  </button>
                </div>
                <div className="d-flex justify-content-between">
                  <table class="table">
                    <thead>
                      <tr>
                        <th scope="col">Project ID</th>
                        <th scope="col">Description</th>
                        <th scope="col">Project Manager</th>
                        <th scope="col">No. of Sprints</th>
                        <th scope="col">Employees</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <th scope="row">{projectId}</th>
                        <td>{description}</td>
                        <td>{projectManager.name}</td>
                        <td>{sprints}</td>
                        <>
                          <td>
                            <ul>
                              {employeeList.map((employee) => (
                                <li>
                                  {employee.firstName} {employee.lastName}
                                </li>
                              ))}
                            </ul>
                          </td>
                        </>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

const EvaluateProject = () => {
  return (
    <>
      <div className="container">
        <div className="row">
          <div className="col-lg-12">
            <Header />
          </div>
        </div>
      </div>
      <Table />
    </>
  );
};

export default EvaluateProject;
